### PR TITLE
Fix unearned bug

### LINKED ISSUE #4: Unearned income not included in net income calculation
From Phil:

>I'm forwarding you an email we got about the calculator and an error that seems to be occurring. I did some poking around and it looks like the monthly unearned income #'s from step 3 are not being pulled over to calculate adjusted income in step 5. As both earned and unearned incomes are considered in the calc process, could we add a line on step 5 that would show "Net unearned income" and have that value referenced in determining adjusted income? I'm sorry I didn't notice this myself sooner- let me know if you have any questions. 

From Katie:

>This is a 1 person Household (Standard Deduction $164)
> * Client has $1327 for SSA
> * Client is 65 and not disabled
> * Client pays rent of $377
> * Utility Allowance $822
>
> So our calculation looks like this:
$1327 Income
minus $164 Standard Deduction (Client’s Income would be considered $1163)
minus $617.50 Shelter Deduction [$822 + 377=$1199 -1/2 client’s Income($1163/2=$581.50)]    
Net Income: $545.50
Based on a net income of $545.50 for a 1 person household, the $28 Benefit is correct. 

See email from Phil at Jan 25, 2019, 11:26 AM

### PR DESCRIPTION
**Pull request by bftrock**
Resolves #4 

The only substantive change is in the `moveStep7` function, where I fixed the jQuery selector to the correct name of the `input`. The bug was that I was selecting a non-existent `input`.

### CODE REVIEW

File: js/main.js [hunk 1]
```diff
@@ -296,7 +278,7 @@ function calcAdjustedIncome() {
   var result = false;
   try {
     var netEarnedInc = Number($("#netEarnedInc").text());
-    var unearnedInc = Number($("#unearnedInc").text());
+    var unearnedInc = Number($("#unearnedIncTotal").text());
```
Comment (bftrock) [inline js/main.js:281]: There is no object named `unearnedInc` and so the resulting `unearnedInc` variable is set to zero, which is a bug.

**Comment by bftrock** [comment]
@mware I'm curious if you're aware of a way to automatically detect problems like this (referencing a non-existent html object).
